# Generated by Django 3.1.1 on 2020-10-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='beg_datetime',
            field=models.DateTimeField(null=True, verbose_name='beg_datetime'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='end_datetime'),
        ),
    ]
