# Generated by Django 3.1.1 on 2020-10-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20201027_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='beg_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_datetime',
        ),
    ]
