# Generated by Django 3.1.1 on 2020-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20201031_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='beg_datetime',
            field=models.DateTimeField(null=True, verbose_name='begin_datetime'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(null=True, verbose_name='end_datetime'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='task_is_finished'),
        ),
    ]
